# ~/.config/shikane/config.toml
# You may have to create the folder and file yourself
# ALSO REMEMBER TO COMMENT OUT THE MONITOR CONFIG IN HYPRLAND CONF
# If you get stuck in booting screen, disable splash
sudo nano /etc/default/grub
and remove splash from GRUB_CMDLINE_LINUX_DEFAULT='nowatchdog nvme_load=YES zswap.enabled=0 loglevel=3'
# --- Your specific profiles ---

[[profile]]
name = "undocked"
exec = [ "sh -lc 'pkill -x wl-mirror || true'" ]
  [[profile.output]]
  search   = "n=eDP-1"
  enable   = true
  position = "0,0"
  scale    = 1.333333

[[profile]]
name = "docked-dual"
exec = [ "sh -lc 'pkill -x wl-mirror || true'" ]
  [[profile.output]]
  search   = "n=DP-11"
  enable   = true
  position = "0,0"

  [[profile.output]]
  search   = "n=DP-12"
  enable   = true
  position = "2560,0"

  [[profile.output]]
  search = "n=eDP-1"
  enable = false

[[profile]]
name = "mirror-externals"
# Clear any previous mirrors first
exec = [ "sh -lc 'pkill -x wl-mirror || true'" ]

  # Laptop panel (mirror source)
  [[profile.output]]
  search = "n=eDP-1"
  enable = true
  # (Optional: for true 1:1 clone, also set the laptop to 1080p@60 if it supports it)
  #mode   = "1920x1080@60Hz"
  #scale  = 1

  # External #1 (forced 1080p@60)
  [[profile.output]]
  search = [ "n%DP-", "n%HDMI-", "n%USB-C" ]
  enable = true
  mode   = "1920x1080@60Hz"
  scale  = 1
  exec   = [
    "sh -lc 'wl-present mirror eDP-1 --fullscreen-output \"$SHIKANE_OUTPUT_NAME\" --fullscreen &'"
  ]

  # External #2 (forced 1080p@60)
  [[profile.output]]
  search = [ "n%DP-", "n%HDMI-", "n%USB-C" ]
  enable = true
  mode   = "1920x1080@60Hz"
  scale  = 1
  exec   = [
    "sh -lc 'wl-present mirror eDP-1 --fullscreen-output \"$SHIKANE_OUTPUT_NAME\" --fullscreen &'"
  ]

  # External #3 (forced 1080p@60)
  [[profile.output]]
  search = [ "n%DP-", "n%HDMI-", "n%USB-C" ]
  enable = true
  mode   = "1920x1080@60Hz"
  scale  = 1
  exec   = [
    "sh -lc 'wl-present mirror eDP-1 --fullscreen-output \"$SHIKANE_OUTPUT_NAME\" --fullscreen &'"
  ]
