# ~/.config/shikane/config.toml
# You may have to create the folder and file yourself
# ALSO REMEMBER TO COMMENT OUT THE MONITOR CONFIG IN HYPRLAND CONF
# If you get stuck in booting screen, disable splash
#sudo nano /etc/default/grub
#and remove splash from GRUB_CMDLINE_LINUX_DEFAULT='nowatchdog nvme_load=YES zswap.enabled=0 loglevel=3'
#sudo grub-mkconfig -o /boot/grub/grub.cfg
# --- Your specific profiles ---

[[profile]]
name = "undocked"
  [[profile.output]]
  search   = "n=eDP-1"
  enable   = true
  position = "0,0"
  scale    = 1.333333

[[profile]]
name = "docked-dual"
  [[profile.output]]
  search   = "n=DP-11"
  enable   = true
  position = "0,0"

  [[profile.output]]
  search   = "n=DP-12"
  enable   = true
  position = "2560,0"

  [[profile.output]]
  search = "n=eDP-1"
  enable = false

[[profile]]
name = "external-any"

  [[profile.output]]
  search = "n=eDP-1"
  enable = true
  scale  = 1.333333
  position = "0,0"

  [[profile.output]]
  search = "/DP-[1-9]"
  enable = true
  mode   = "1920x1080@60Hz"
  scale  = 1
  position = "1692,0"
